name: Linux ARM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ARM runner
      uses: pguyot/arm-runner-action@v2.6.3
      with:
        commands: sudo apt update & sudo apt-get -y install build-essential cmake clang ninja-build libgtk-3-dev
        image_additional_mb: 5000
        base_image: raspios_lite_arm64:latest
        
        
        
        
        


    # - name: Install Dependencies
    #   run : sudo apt-get update & sudo apt-get install build-essential cmake clang ninja-build
      
    # - uses: actions/checkout@v4
    # - name: set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     cache: gradle
        
    # - name: Flutter action
    #   # You may pin to the exact commit or the version.
    #   # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
    #   uses: subosito/flutter-action@v2.14.0
    #   with:
    #     flutter-version: 3.0.5
        
    # - name: Test Installation
    #   run: flutter doctor -v
      
    # - name: Buid Linux
    #   run: flutter build linux --release
    # - name: Upload Build Zip
    #   uses: actions/upload-artifact@v4.3.4
    #   with:
    #     path: ./build/linux/x64/release/bundle
