name: Linux ARM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted 
    steps:
    - name: Configure Cloudflare DNS
      run: echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1" | sudo tee /etc/resolv.conf
      
    - name: Install Dependencies
      run : sudo apt-get install -y build-essential cmake clang ninja-build 
      
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Flutter action
      run: sudo snap install flutter --classic
      
    - name: Test Installation
      run: flutter doctor -v
      
    # - name: Buid Linux
    #   run: flutter build linux --release
    # - name: Upload Build Zip
    #   uses: actions/upload-artifact@v4.3.4
    #   with:
    #     path: ./build/linux/x64/release/bundle

 
