name: Linux ARM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          shell: /bin/bash
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt update -y
            apt-get install git curl cmake clang snapd ninja-build -y
            ls 
            whoami
            systemctl start snapd.service
            snap install snap-core
            snap install snap-store
            snap install flutter --classic
            flutter doctor -v
            


           
      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.value }}"

            




    # - name: Install Dependencies
    #   run : sudo apt-get update & sudo apt-get install build-essential cmake clang ninja-build
      
    # - uses: actions/checkout@v4
    # - name: set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     cache: gradle
        
    # - name: Flutter action
    #   # You may pin to the exact commit or the version.
    #   # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
    #   uses: subosito/flutter-action@v2.14.0
    #   with:
    #     flutter-version: 3.0.5
        
    # - name: Test Installation
    #   run: flutter doctor -v
      
    # - name: Buid Linux
    #   run: flutter build linux --release
    # - name: Upload Build Zip
    #   uses: actions/upload-artifact@v4.3.4
    #   with:
    #     path: ./build/linux/x64/release/bundle
