name: Linux ARM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: warp-custom-build-arm64
    steps:
    - name: Configure Cloudflare DNS
      run: echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1" | sudo tee /etc/resolv.conf
      
    - name: Install Dependencies
      run : sudo apt-get install -y build-essential git cmake clang ninja-build curl wget snapd

    # - name: Flutter action
    #   # You may pin to the exact commit or the version.
    #   # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
    #   uses: subosito/flutter-action@v2.14.0
    #   with:
    #     flutter-version: 3.0.5
    - name: Snap Install
      run: sudo snap install core

      
    - name: Flutter Install
      run: mkdir build
      

    - name: Flutter Install
      run: wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.5-stable.tar.xz
      working-directory: build

    - name: Flutter Install
      run: tar xf flutter_linux_3.0.5-stable.tar.xz /usr/bin/flutter
      working-directory: build

    # - name: Flutter Install
    #   run: mv -v ./flutter/bin/* /usr/bin/
    #   working-directory: build
      

    - name: Migrate to Stable
      run: ls /usr/bin
      
    # - name: Set Version to 3.0.5
    #   run: flutter downgrade 3.0.5
      
    - name: Test Installation
      run: flutter doctor -v

      
    - name: Git Clone
      run: git clone https://github.com/c9-labs/newsdrip.git
      
    - name: Enter Directory
      run: cd newsdrip
      
    - name: Test Installation Directory
      run: ls
      
    - name: Buid Linux
      run: ../build/flutter/bin/flutter build linux --release
      working-directory: newsdrip
      
    - name: Upload Build Zip
      uses: actions/upload-artifact@v4.3.4
      with:
        path: ./newsdrip/build/linux/

    
