name: Linux ARM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: warp-custom-build-arm64
    steps:
    - name: Configure Cloudflare DNS
      run: echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1" | sudo tee /etc/resolv.conf
      
    - name: Install Dependencies
      run : sudo apt-get install -y build-essential cmake clang ninja-build curl wget snapd

    # - name: Flutter action
    #   # You may pin to the exact commit or the version.
    #   # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
    #   uses: subosito/flutter-action@v2.14.0
    #   with:
    #     flutter-version: 3.0.5
    - name: Snap Install
      run: sudo snap install core

    - name: Flutter Install
      run: sudo snap intall flutter --classic
      
    - name: Test Installation
      run: flutter doctor -v
      
    - name: Test Installation
      run: flutter -version & ls
      
    - name: Buid Linux
      run: flutter build linux --release
      
    - name: Upload Build Zip
      uses: actions/upload-artifact@v4.3.4
      with:
        path: ./build/linux/

    
