name: Linux CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Setup Cloudflare
      run: echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1" | sudo tee /etc/resolv.conf
      
    - name: Log IP
      run: curl https://ifconfig.me/ip 
      
    - name: Install Dependencies
      run : sudo apt update -y -s & sudo apt-get install git build-essential cmake clang ninja-build libgtk-3-dev -y -s
      
    # - uses: actions/checkout@v4
    # - name: set up JDK 11
    #   uses: actions/setup-java@v3
    #   with:
    #     java-version: '11'
    #     distribution: 'temurin'
    #     cache: gradle
        
    - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56
      uses: subosito/flutter-action@v2.14.0
      with:
        flutter-version: 3.0.5
        
    - name: Test Installation
      run: |
            sudo apt install -y ninja-build
            sudo apt install -y libgtk-3-dev
            flutter doctor -v

            
      
    - name: Buid Linux
      working-directory: ./newsdrip
      run: |
            ls
      
    - name: Upload Build Zip
      uses: actions/upload-artifact@v4.3.4
      with:
        path: ./build/linux/x64/release/bundle
