name: Linux ARM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: warp-custom-build-arm64
    steps:
    - name: Configure Cloudflare DNS
      run: echo -e "nameserver 1.1.1.1\nnameserver 1.0.0.1" | sudo tee /etc/resolv.conf
      
    - name: Install Dependencies
      run : sudo apt-get install -y build-essential cmake clang ninja-build 
      
    - name: Flutter action
      run: sudo snap install flutter --classic
            
    - name: Test Installation
      run: flutter -version & ls
      
    - name: Buid Linux
      run: flutter build linux --release
      
    - name: Upload Build Zip
      uses: actions/upload-artifact@v4.3.4
      with:
        path: ./build/linux/x64/release/bundle

    
